# Only include counties within this state (give as 2 digit FIPS)
# "10" for Delaware (3 counties), "08" for Colorado (64 counties)
filterstate: null

# Current options: counties (full-country), dummy (5-counties)
dataset: counties

# First and last month of the simulation
startmonth: 1/2001
endmonth: 12/2010

# First entry in VIC_WB to include
startweather: 616

# Months per time step
timestep: 12
