# Only include counties within this state (give as 2 digit FIPS)
# "10" for Delaware (3 counties), "08" for Colorado (64 counties)
filterstate: null

# Current options: counties (full-country), dummy (5-counties)
dataset: paleo

# Months per time step
timestep: 1
