# Only include counties within this state (give as 2 digit FIPS)
# "10" for Delaware (3 counties), "08" for Colorado (64 counties)
filterstate: "36"

# Current options: counties (full-country), dummy (5-counties)
dataset: counties

# First and last month of the simulation
startmonth: 1/2009 #10/2009
endmonth: 12/2014

# First entry in VIC_WB to include
startweather: 603 #612

# Months per time step
timestep: 1

# Type of optimization: "SW" for only surface water, "SWGW" for the conjunctive use of both resources
optimtype: "SWGW"

# Reservoir: set to "zero" to set all reservoir storage capacities to 0
rescap: "full"

# Urban demand:
urbandemand-path: demand/urbandemand_May11.csv
urbandemand-column: per_capita
urbandemand-transform: repcap
urbandemand-index: FIPS_county

