filterstate: null
netset: usa
startmonth: 10/2010
endmonth: 9/2011
startweather: 600
timestep: 6
optimtype: SWGW

# Cost configuration : choices are basic/extractiongw/extractionswgw
watercostmodel: extractiongw

# Groundwater configuration : initialisation of head. choices: null/drawdown2010
rescap: zero
