# Only include counties within this state (give as 2 digit FIPS)
# "10" for Delaware (3 counties), "08" for Colorado (64 counties)
filterstate: null

# Current options: usa (full-country), dummy (5-counties)
netset: usa

# First and last month of the simulation
startmonth: 10/2000
endmonth: 9/2010

# First entry in VIC_WB to include
startweather: 612

# Months per time step
timestep: 6

urbandemand-path: demand/urbandemand_May11.csv
urbandemand-column: per_capita
urbandemand-transform: repcap
urbandemand-index: FIPS_county
