# Only include counties within this state (give as 2 digit FIPS)
# "10" for Delaware (3 counties), "08" for Colorado (64 counties)
filterstate: "08"

# Current options: usa (full-country), dummy (5-counties)
dataset: counties 

# First and last month of the simulation
startmonth: 1/2010    #1/2010   1951
endmonth: 12/2010  #12/2010

# First entry in VIC_WB to include
#startweather: 292 #10th percentile 
#startweather: 340 #median number 29 
#startweather: 424 #90th 
#startweather: 628 #extreme drought year 2002
#startweather: 16 #Jan 1951
startweather: 712 #Jan2009

# Cost configuration
watercost-extraction: true
watercost-treatment: false

# Months per time step
timestep: 12

# Type of optimization : "SW" if only surface water, "SWGW" if conjunctive use of surface and groundwater to meet demand
optimtype: "SWGW"
# Reservoir capacity : set rescap to zero 
rescap: "full"


urbandemand-path: demand/urbandemand_May11.csv
urbandemand-column: per_capita
urbandemand-transform: repcap
urbandemand-index: FIPS_county