<<<<<<< HEAD:configs/standard-1year-colorado.yml
# Only include counties within this state (give as 2 digit FIPS)
# "10" for Delaware (3 counties), "08" for Colorado (64 counties)
filterstate: "08"

# Current options: usa (full-country), dummy (5-counties)
netset: usa

# First and last month of the simulation
startmonth: 1/2010
endmonth: 12/2010

# First entry in VIC_WB to include
startweather: 720

# Months per time step
timestep: 1

# Type of optimization : "SW" if only surface water, "SWGW" if conjunctive use of surface and groundwater to meet demand
=======
filterstate: null
netset: usa
startmonth: 10/2010
endmonth: 9/2011
startweather: 600
timestep: 6
>>>>>>> master:configs/standard-1year.yml
optimtype: SWGW
rescap: zero
